compressionLevel: 0
enableScripts: false
enableTelemetry: false
enableGlobalCache: false

nodeLinker: pnpm
globalFolder: .yarn/global # Workaround for 'EXDEV: cross-device link not permitted' errors on GHA

yarnPath: .yarn/releases/yarn-4.11.0.cjs
