approvedGitRepositories:
  - "**"

compressionLevel: 0

enableGlobalCache: false

enableScripts: false

enableTelemetry: false

globalFolder: .yarn/global

nodeLinker: pnpm

npmMinimalAgeGate: 0

yarnPath: .yarn/releases/yarn-4.17.0.cjs
